---
abstract: 'Language-neutral metadata for your code'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rinci
requires:
  DefHash: v1.0.3
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Rinci
  homepage: https://metacpan.org/release/Rinci
  repository: git://github.com/sharyanto/perl-Rinci.git
version: 1.1.41
