---
abstract: 'Language-neutral metadata for your code'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rinci
resources:
  homepage: http://metacpan.org/release/Rinci
  repository: http://github.com/sharyanto/perl-Rinci
version: 1.1.0
